#include "PubKeyMAC_Asn1.h"

ASN1_SEQUENCE(PubKeyMAC) = {
	ASN1_SIMPLE(PubKeyMAC,pubKeyName,ASN1_PRINTABLESTRING),
	ASN1_SIMPLE(PubKeyMAC,MACKey,ASN1_OCTET_STRING),
	ASN1_SIMPLE(PubKeyMAC,MACValue,ASN1_OCTET_STRING)
}ASN1_SEQUENCE_END(PubKeyMAC);

IMPLEMENT_ASN1_FUNCTIONS(PubKeyMAC);